<a href="https://colab.research.google.com/github/codeworkshopou/Data-Management-and-Statistics-in-Python/blob/main/Copy_of_DM_v4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data management: Day 1

Throughout this tutorial, we will use the `pandas` Python module. This is a very useful module for data analyses and management. Since `pandas` is not a built-in Python module, you might need to install it locally if you are not using this Google Colab notebook. For details, please see instructions [here](https://pandas.pydata.org/getting_started.html).

We can import the `pandas` module with:

In [ ]:
import pandas as pd


# Contents 

[2](#Data-reading): Data reading

[3](#Data-exploration): Data exploration

[4](#Column-selection): Column selection

[5](#Column-modification): Column modification

[6](#filtering): Filtering

[7](#sorting): Sorting

[8](#Merge): Merge

[9](#grouping): Grouping
    

# Data reading

If we have a csv-formated file locally stored, `pandas` can read it directly with the `pd.read_csv` function:

```python
df = pd.read_csv('PATH/TO/FILE')
```
If the file is rather available online, you can specify the URL inside the function:

```python
df = pd.read_csv('URL/ROUTE')
```

The later is our case. We will donwload our study dataset from a URL path:


In [ ]:
url = "https://raw.githubusercontent.com/ulises-rosas/code/main/CalHou.csv"
housing = pd.read_csv(url)
type(housing)

pandas.core.frame.DataFrame

As seen with the function `type`, the read data is a `pandas.core.frame.DataFrame` object, and it contains many methods that will help us to manipulate datasets

For reference, here is the description of the "California housing" dataset columns:

- MedInc    : median income in block group (hundreds of thousands of dollars)
- HouseAge  : median house age in block group
- AveRooms  : average number of rooms per household
- AveBedrms : average number of bedrooms per household
- Population : block group population
- AveOccup  : average number of household members
- Latitude  : block group latitude
- Longitude : block group longitude


# Data exploration

We can summarize column information by using the `.info()` method directly on the table. From below, we can see that the `housing` dataset contains 20640 rows and 9 columns:

In [ ]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


we can see the first or last five rows with the `.head()` and `.tail()` methods respectively. By default, five rows are selected. 

In [ ]:
housing.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

Note that the above output is still a `pandas.core.frame.DataFrame` object, so you can still apply methods on top

In [ ]:
housing.tail()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894

`.sample()` method is used to randomly sample rows of the dataset. In this case, we specify the number of rows selected.

In [ ]:
housing.sample(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
6343   0.4999      52.0  3.875000   0.562500        44.0  2.750000     34.06   
16859  2.2250      41.0  5.157895   1.052632        68.0  3.578947     37.64   
128    7.5544      40.0  7.631498   1.030581      1616.0  2.470948     37.83   
10177  3.6471      12.0  4.628378   1.239865      1022.0  3.452703     33.86   
13919  1.3571      34.0  9.144208   2.971631       890.0  2.104019     34.20   

       Longitude  MedHouseVal  
6343     -117.75        1.125  
16859    -122.42        2.125  
128      -122.21        4.115  
10177    -117.97        1.417  
13919    -115.85        0.410

We can quickly get basic statistics from each column with the `.describe()` method:

In [ ]:
housing.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude   MedHouseVal  
count  20640.000000  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704      2.068558  
std       10.386050      2.135952      2.003532      1.153956  
min        0.692308     32.540000   -124.350000      0.149990  
25%        2.429741     33.930000   -121.800000      1.196000  
50%        2.818116     34.260000   -118.490000      1.797000  
75%        3.282261     37.710000   -118.010000      2.647250  
max     1243.333333     41.950000   -114.310000      5.000010

## Mini-challenge:

Sample two rows from the first five rows of the dataset

In [ ]:
# you answer here

# Column selection

If we want to list all available columns, we use the `.columns` method:

In [ ]:
housing.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

If we want to inspect an specific column, we can select it by using the following structure:

```python
df['column']
```

For example, if we want to get the first two rows of `AveRooms` column, we will use:

In [ ]:
housing['AveRooms'].head(2)

0    6.984127
1    6.238137
Name: AveRooms, dtype: float64

Similarly, we wanto to select more than one column, we can select them by using a list of names:

```python
df[['column 1', 'column 2']]
```
For example, below we use the list `['Population', 'AveRooms']` to select the fist two rows

In [ ]:
housing[['Population', 'AveRooms']].head(2)

Population  AveRooms
0       322.0  6.984127
1      2401.0  6.238137

Another table can be created by storing above results

In [ ]:
df2 = housing[['Population', 'AveRooms']].head(2)
df2

Population  AveRooms
0       322.0  6.984127
1      2401.0  6.238137

If you know the exact location of a column (i.e., index), you can also call the column, as well as the rows, by using the method `.iloc`. In the following line, for example, `0:2` denotes the first two columns, and `[4,2]` denotes columns 4 and 2

In [ ]:
housing.iloc[0:2, [4,2]]

Population  AveRooms
0       322.0  6.984127
1      2401.0  6.238137

# Column modification

We can generate a new column on the fly by directly assigning values into the new column name. The structure of the assignment should follow this structure:

```python
df['new column'] = 'new values'
```
where `'new values'` is a series of values that `'new column'` will store. For example, we can create a new column called `'income_cat'` that, for each row, has `True` if the value of the median income is below 3.87, and `False` otherwise:

In [ ]:
housing['income_cat'] =  housing['MedInc'] < 3.87
housing[['MedInc', 'income_cat']].sample(8)

MedInc  income_cat
498     2.2431        True
5335    3.6976        True
18513   4.0417       False
6184    5.0123       False
139     6.3302       False
4656    2.1736        True
1564   12.5915       False
12131   3.2148        True

## Challenge:

Create a new column called `is_pop_large` that label rows `False` if the block group population is below the overall average, and `True` otherwise. Select the  `Population` column and the previously created `is_pop_large` column, and sample 8 rows.

*Hint*: Use results previously obtained from `housing.describe()` to create bins



In [ ]:
# your solution


`pandas` can also crate more complex categories. In the example below, we create a column storing income categories based on the median income:

In [ ]:
# crates more complex categories based on median income
housing['income_cat'] = pd.cut( housing['MedInc'],
                                bins   = [0., 1.5, 3.0, 4.5, 6.0, 16],
                                labels = [  1,   2,   3,   4,   5   ] ) 

housing[['MedInc', 'income_cat']].sample(8)

MedInc income_cat
11231  4.3269          3
4853   1.8564          2
18841  2.2024          2
158    7.5080          5
2970   7.1837          5
15099  2.5430          2
13622  1.4620          1
15917  2.3087          2

by default, bins includes the rightmost edge (i.e., `(0, 1.5]`, `(1.5, 3.0]`). You can change this behaviour (i.e., `[0, 1.5)`, `[1.5, 3.0)`)with the argument `right = False`



# Filtering

As seen before, we can generate a series of boolean values by using comparison operators (e.g., `<`, `>`, `==`). In the example below, we will compare values of the `'Population'` column with 2000:

In [ ]:
# generates a series of boolean values
housing['Population'] > 2000

0        False
1         True
2        False
3        False
4        False
         ...  
20635    False
20636    False
20637    False
20638    False
20639    False
Name: Population, Length: 20640, dtype: bool

Series of bolean values is pretty useful for 

In [ ]:
# which can be used to filter rows
housing[ housing['Population'] > 2000 ].head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
1    8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
95   2.0096      36.0  2.294016   1.066294      3469.0  1.493328     37.80   
96   2.8345      31.0  3.894915   1.127966      2048.0  1.735593     37.82   
98   1.2185      22.0  2.945600   1.016000      2024.0  1.619200     37.82   
100  2.4912      29.0  3.724800   1.131200      2304.0  1.843200     37.81   

     Longitude  MedHouseVal income_cat  
1      -122.22        3.585          5  
95     -122.26        1.300          2  
96     -122.26        1.838          2  
98     -122.26        1.700          1  
100    -122.25        2.578          2

Note that the `'Population'` column contains values greater than 2000. If we stored above table and print the number of rows, we will notice that the number of rows have been reduced

In [ ]:
more_populated = housing[ housing['Population'] > 2000 ]
len(more_populated)

3680

The original number of rows is 20640.

## Question:

>What is the average latitude of the highest income category?

*Remark*: the `.mean()` method can be applied to filtered rows, so you might not need to implement a function that outputs averages from scratch

In [ ]:
# your answer

After filtering, selected rows can be mutated with a custom set of values by using the `.loc` method. For example, for rows whose population is less than 2000, we set the average number of room equal to 4

In [ ]:
housing.loc[ housing['Population'] < 2000 , 'AveRooms'] = 4
housing.loc[ housing['Population'] < 2000 , ['Population', 'AveRooms'] ]

Population  AveRooms
0           322.0       4.0
2           496.0       4.0
3           558.0       4.0
4           565.0       4.0
5           413.0       4.0
...           ...       ...
20635       845.0       4.0
20636       356.0       4.0
20637      1007.0       4.0
20638       741.0       4.0
20639      1387.0       4.0

[16956 rows x 2 columns]

While we have applied one conditional at a time, multiple conditionals can be used to filter table rows. Multiple conditionals generate multiple sets of boolean series, and their intersection (i.e., `&` operator) or union (i.e.,  `|` operator) among sets are used to finally filter rows. For example, if we want to know what are the income categories for the population between 2000 and 2003, we use the following line:

In [ ]:
housing.loc[ (housing['Population'] > 2000) & (housing['Population'] < 2003), ['Population','income_cat']]

Population income_cat
2114       2002.0          1
9690       2002.0          3
14681      2001.0          4
14876      2002.0          2
17139      2002.0          3
17660      2002.0          3
18670      2001.0          4
20343      2002.0          4

Note that each conditional is surrounded between parenthesis and their interesection is obtained by using the `&` operator.

## Question

>What are the average house values between 40-42 latitudes, and between 30-32 latitudes?

In [ ]:
# your answer


# Sorting

We can order rows of a table in function a given column values by using the `.sort_values()` method. In the following example, we will order rows in function of income (i.e., `'MedInc'`), and we will print the first five rows:

In [ ]:
housing.sort_values('MedInc').head()

MedInc  HouseAge  AveRooms  AveBedrms  Population   AveOccup  Latitude  \
4861   0.4999      29.0  2.373272   1.055300      2690.0  12.396313     34.02   
7125   0.4999      36.0  4.000000   0.833333        15.0   2.500000     33.90   
6688   0.4999      28.0  4.000000   1.870968       142.0   4.580645     34.15   
19800  0.4999      15.0  4.000000   2.561404       131.0   2.298246     40.43   
6343   0.4999      52.0  4.000000   0.562500        44.0   2.750000     34.06   

       Longitude  MedHouseVal income_cat  
4861     -118.28      5.00001          1  
7125     -118.04      1.62500          1  
6688     -118.08      5.00001          1  
19800    -123.32      0.56700          1  
6343     -117.75      1.12500          1

We can inverse the order by using the argument `ascending = False`

In [ ]:
# invert 
housing.sort_values('MedInc', ascending=False).head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
4352   15.0001      37.0       4.0   1.425532       100.0  2.127660     34.10   
10673  15.0001      13.0       4.0   0.993958      1865.0  2.817221     33.62   
8849   15.0001      52.0       4.0   1.062954      1266.0  3.065375     34.08   
4606   15.0001      52.0       4.0   1.062112       531.0  3.298137     34.07   
5257   15.0001      42.0       4.0   1.161290       829.0  2.674194     34.06   

       Longitude  MedHouseVal income_cat  
4352     -118.37      5.00001          5  
10673    -117.85      5.00001          5  
8849     -118.40      5.00001          5  
4606     -118.33      5.00001          5  
5257     -118.49      5.00001          5

## Question:

>What are the coordinates of the three oldest houses with income caterogy 5?

In [ ]:
# your answer


# Merge

Merge allow us to intersect multiple tables in function of key column (i.e., a common column between tables). While combining tables is the essence of this functionality, there different ways this can be done:


<!-- <p align="center"> -->
<img src="https://raw.githubusercontent.com/ulises-rosas/code/main/images/merge_types.png" width="250" height="280">
<!-- </p> -->

Before making an example of this functionality, let's download another datasets. We are going to use [The NYC squirrel census](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-10-29) dataset.

In [ ]:
squi_url = "https://raw.githubusercontent.com/ulises-rosas/code/main/squirrel_base.csv"
squirrels = pd.read_csv(squi_url)
squirrels.head(2)

unique_squirrel_id        lat       long  indifferent primary_fur_color  \
0     37F-PM-1014-03  40.794082 -73.956134        False               NaN   
1      2E-AM-1010-03  40.766718 -73.976831         True          Cinnamon   

  highlight_fur_color  
0                 NaN  
1                 NaN

In [ ]:
behavior_url = "https://raw.githubusercontent.com/ulises-rosas/code/main/squirrel_behavior.csv"
behavior = pd.read_csv(behavior_url)
behavior.head(2)

unique_squirrel_id  running  chasing  climbing  eating  foraging
0     37F-PM-1014-03    False    False     False   False     False
1      2E-AM-1010-03    False    False      True   False     False

In [ ]:
squirrels = pd.merge( squirrels, behavior, how = 'left', on = 'unique_squirrel_id')
squirrels.head(2)

unique_squirrel_id        lat       long  indifferent primary_fur_color  \
0     37F-PM-1014-03  40.794082 -73.956134        False               NaN   
1      2E-AM-1010-03  40.766718 -73.976831         True          Cinnamon   

  highlight_fur_color  running  chasing  climbing  eating  foraging  
0                 NaN    False    False     False   False     False  
1                 NaN    False    False      True   False     False

## Challenge:

Complete the `squirrels` table by merging squirrel sounds from this url path: "https://raw.githubusercontent.com/ulises-rosas/code/main/squirrel_sounds.csv"



# Grouping

Grouping allows us to apply a given function specifically to rows that are part of the same category. The above dataset contains various measures of squirrels from NYC. If we want to know the frequency of fur color in our dataset, we can use the `.groupby` method over the column `'primary_fur_color'`, and then count rows:

In [ ]:
squirrels.groupby('primary_fur_color').apply(len) 

primary_fur_color
Black        103
Cinnamon     392
Gray        2473
dtype: int64

`len` function is used to count grouped rows.

## Challenge:

Use a `for-loop` to get same results from above chunk.

*Note*: As a reminder, a typical `for-loop` has the following strucuture

>```python
>for i in values:
>    # a given operation 
>    # over i, e.g., print
>    print(i)
>```

You can use above structure to filter the table and count the number of rows


In [ ]:
# your solution


`pandas` can handle more complex groupings that might be tedious to implement in a regular `for-loop` due to the number of conditionals. We just need to give a list of grouping columns into the `groupby` function. 

For instance, if we want to know how many squirrels were seen climbing for each group of fur color, we can use the following line:

In [ ]:
squirrels.groupby(['primary_fur_color','climbing']).apply(len)

primary_fur_color  climbing
Black              False         78
                   True          25
Cinnamon           False        310
                   True          82
Gray               False       1930
                   True         533
dtype: int64

## Question

> How many squirrels of Gray fur were indifferent to human precense while eating?

*Note*: `indifferent` and `eating` columns depicts if the squirrel was seen indiffirent to humans and eating, respectively

In [ ]:
# you answer


From the above examples, we have relied on the built-in Python `len`. However, we can introduce custom functions into the `apply` function. For instance, if we create a custom function such as the variance, we can apply the above function to grouped rows such that we can approach the sparsity in the longitude axis given the squirrel fur color

In [ ]:
# my custom function
def variance(values):
    sig = 0
    x_bar = sum(values)/len(values)
    for x in values:
        sig += ( x - x_bar )**2
    return sig

# apply to above function to
# the grouped 'long' column
squirrels.groupby('primary_fur_color')['long'].apply(variance)

primary_fur_color
Black       0.004400
Cinnamon    0.025248
Gray        0.144516
Name: long, dtype: float64